// Self-hosts the three brand faces.
//
// Previously the site pulled them from Google Fonts: two render-blocking
// requests, two third-party hosts before first paint, and every visitor's IP
// disclosed to Google on page load (the basis of the German Google Fonts
// ruling). IBM Plex and Spectral are both SIL Open Font Licence, so hosting
// them ourselves is permitted; the licence travels in public/fonts/OFL.txt.
//
// Only the weights the site actually uses are fetched.
import { writeFile, mkdir } from "node:fs/promises";

const FACES = [
  ["IBM+Plex+Sans", "ibm-plex-sans", [[400,0],[500,0],[600,0],[700,0]]],
  ["IBM+Plex+Mono", "ibm-plex-mono", [[400,0],[500,0],[600,0]]],
  ["Spectral",      "spectral",      [[200,0],[300,0],[400,0],[200,1],[300,1],[400,1]]],
];

await mkdir("public/fonts", { recursive: true });
const UA = "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120 Safari/537.36";
let css = `/* Self-hosted brand faces. IBM Plex and Spectral are SIL OFL 1.1.
   Generated by scripts/fetch-fonts.mjs - do not edit by hand. */\n`;
let count = 0;

for (const [gname, slug, variants] of FACES) {
  for (const [weight, italic] of variants) {
    const axis = italic ? `ital,wght@1,${weight}` : `ital,wght@0,${weight}`;
    const url = `https://fonts.googleapis.com/css2?family=${gname}:${axis}&display=swap`;
    const sheet = await (await fetch(url, { headers: { "User-Agent": UA } })).text();
    // take the latin subset block
    const blocks = sheet.split("@font-face").filter(b => b.includes("U+0000-00FF"));
    const block = blocks[0] || sheet.split("@font-face").pop();
    const woff2 = block.match(/url\((https:\/\/[^)]+\.woff2)\)/);
    const range = block.match(/unicode-range:\s*([^;]+);/);
    if (!woff2) { console.log(`  MISS ${slug} ${weight}${italic ? "i" : ""}`); continue; }
    const bytes = Buffer.from(await (await fetch(woff2[1])).arrayBuffer());
    const file = `${slug}-${weight}${italic ? "-italic" : ""}.woff2`;
    await writeFile(`public/fonts/${file}`, bytes);
    css += `@font-face{font-family:'${gname.replace(/\+/g, " ")}';font-style:${italic ? "italic" : "normal"};`
         + `font-weight:${weight};font-display:swap;src:url(/fonts/${file}) format('woff2');`
         + (range ? `unicode-range:${range[1].trim()};` : "") + `}\n`;
    console.log(`  ${file.padEnd(34)} ${Math.round(bytes.length / 1024)}KB`);
    count++;
  }
}
await writeFile("public/css/fonts.css", css);
console.log(`\n${count} faces self-hosted -> public/css/fonts.css`);
